// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ItemResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ItemResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ItemID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemID) Reset()         { *m = ItemID{} }
func (m *ItemID) String() string { return proto.CompactTextString(m) }
func (*ItemID) ProtoMessage()    {}
func (*ItemID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *ItemID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemID.Unmarshal(m, b)
}
func (m *ItemID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemID.Marshal(b, m, deterministic)
}
func (m *ItemID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemID.Merge(m, src)
}
func (m *ItemID) XXX_Size() int {
	return xxx_messageInfo_ItemID.Size(m)
}
func (m *ItemID) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemID.DiscardUnknown(m)
}

var xxx_messageInfo_ItemID proto.InternalMessageInfo

func (m *ItemID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ItemMessageResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemMessageResponse) Reset()         { *m = ItemMessageResponse{} }
func (m *ItemMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ItemMessageResponse) ProtoMessage()    {}
func (*ItemMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *ItemMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemMessageResponse.Unmarshal(m, b)
}
func (m *ItemMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemMessageResponse.Marshal(b, m, deterministic)
}
func (m *ItemMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemMessageResponse.Merge(m, src)
}
func (m *ItemMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ItemMessageResponse.Size(m)
}
func (m *ItemMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemMessageResponse proto.InternalMessageInfo

func (m *ItemMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ItemRequest)(nil), "ItemRequest")
	proto.RegisterType((*ItemResponse)(nil), "ItemResponse")
	proto.RegisterType((*ItemID)(nil), "ItemID")
	proto.RegisterType((*ItemMessageResponse)(nil), "ItemMessageResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x29, 0x2b, 0xbe, 0x4d, 0x0f, 0x99, 0x87, 0xe2, 0x69, 0x54, 0x90, 0xc1, 0x68,
	0x02, 0xfa, 0x09, 0xb4, 0x03, 0xe9, 0xc1, 0xcb, 0xa6, 0x17, 0x6f, 0x5d, 0xf2, 0xa8, 0x01, 0x9b,
	0xc4, 0x24, 0x15, 0xfc, 0x6a, 0x7e, 0x3a, 0x69, 0x5a, 0x4b, 0x41, 0x0f, 0xe2, 0x29, 0x79, 0xef,
	0xf7, 0xe7, 0x97, 0xbc, 0x04, 0x96, 0xc6, 0x6a, 0xaf, 0x99, 0x43, 0xfb, 0x2e, 0x39, 0xd2, 0x50,
	0xa5, 0x39, 0xcc, 0x0b, 0x8f, 0xf5, 0x0e, 0xdf, 0x1a, 0x74, 0x9e, 0x10, 0x38, 0x56, 0x65, 0x8d,
	0x49, 0xb4, 0x8a, 0xd6, 0x27, 0xbb, 0xb0, 0x27, 0x2b, 0x98, 0x0b, 0x74, 0xdc, 0x4a, 0xe3, 0xa5,
	0x56, 0xc9, 0x34, 0xa0, 0x71, 0x2b, 0x7d, 0x84, 0x45, 0x27, 0x71, 0x46, 0x2b, 0x87, 0xff, 0xb3,
	0x90, 0x33, 0x98, 0x4a, 0x91, 0x1c, 0x05, 0x30, 0x95, 0x22, 0x4d, 0x60, 0xd6, 0x5a, 0x8b, 0x6d,
	0x4f, 0xa2, 0x81, 0x30, 0x58, 0xb6, 0xe4, 0x01, 0x9d, 0x2b, 0x2b, 0x1c, 0x8e, 0x4d, 0x20, 0xae,
	0xbb, 0x56, 0x9f, 0xfd, 0x2e, 0xaf, 0x3f, 0x23, 0x80, 0xbc, 0xb4, 0xfb, 0x6e, 0x74, 0xb2, 0x01,
	0xc8, 0x2d, 0x96, 0x1e, 0x5b, 0x0b, 0x59, 0xd0, 0xd1, 0x0b, 0x5c, 0x9c, 0xd2, 0xf1, 0x28, 0xe9,
	0x84, 0x5c, 0x42, 0x7c, 0x8f, 0x3e, 0x24, 0x63, 0xda, 0x5d, 0xe8, 0x67, 0x68, 0x03, 0xf0, 0x64,
	0xc4, 0x1f, 0x8d, 0x19, 0xc0, 0x16, 0x5f, 0xb1, 0x0f, 0x0f, 0xd2, 0x73, 0xfa, 0xcb, 0x50, 0xe9,
	0xe4, 0x6e, 0xfd, 0x7c, 0x55, 0x49, 0xff, 0xd2, 0x1c, 0x28, 0xd7, 0x35, 0xbb, 0x55, 0x5e, 0xab,
	0x8f, 0x62, 0xcf, 0x2a, 0x9d, 0x55, 0xd6, 0xf0, 0x8c, 0xdb, 0x46, 0xb0, 0xf0, 0x99, 0x87, 0x59,
	0x58, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x46, 0x10, 0x5d, 0xea, 0x01, 0x00, 0x00,
}
